name = "UnitaryTransformations"
uuid = "2aaaa306-0b60-42d5-89de-b99f2615351e"
version = "0.1.0"
authors = ["Volker Karle"]

[deps]
QuantumAlgebra = "1b9008d5-2a9d-4901-8cfb-44bb87795b64"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[sources]
QuantumAlgebra = {url = "https://github.com/volkerkarle/QuantumAlgebra.jl"}

[compat]
QuantumAlgebra = "1.6"
Symbolics = "5, 6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
